### ISSUE TITLE
Whenever I click on Available Book, the System logs out. 

### ISSUE THREAD

**Issue by manandharsamyak** [RahulParajulee/LibraryManagementSystem#5]
![image](https://user-images.githubusercontent.com/81407810/118371844-2430cb00-b5ce-11eb-93d6-2cd02805ff45.png)
**when I try to view the available books in the system, the system logs out**

**Comment by RahulParajulee** [comment]
I am sorry for this issue. I think I have linked the wrong page in that button. I will soon fix this one.

**Comment by RahulParajulee** [comment]
The issue have been fixed. Please check the updated code in the respiratory.

**Comment by manandharsamyak** [comment]
Yes, checked the code. It is working properly now. 
Thank you
