### ISSUE TITLE
Book Request button is not inside the specific box.

### ISSUE THREAD

**Issue by manandharsamyak** [RahulParajulee/LibraryManagementSystem#6]
![image](https://user-images.githubusercontent.com/81407810/118371900-6f4ade00-b5ce-11eb-8049-ad7dc2224d10.png)
The CSS is not properly working in the request book button which is in the admin home page

**Comment by RahulParajulee** [comment]
Oh... Sorry for the inconvenience. The styling part of this page will soon fixed by Sulab Bikram Malla.

**Comment by Sulab7149** [comment]
Thank you for your feedback. I am currently fixing that problem. I'll provide the function page as soon as I can fix that.

**Comment by RahulParajulee** [comment]
Ok, if some problems occured kindly inform us.

**Comment by Sulab7149** [comment]
Thank you for the patience. There was a slight mistake on CSS file. Instead of adding the dedicate class we accidently added wrong class. So, we have corrected and the page looks fine. If you have further doubt on the code please feel free to check the updated codes.
