### ISSUE TITLE
The website is not Responsive

### ISSUE THREAD

**Issue by manandharsamyak** [RahulParajulee/LibraryManagementSystem#7]
![image](https://user-images.githubusercontent.com/81407810/118371980-d6689280-b5ce-11eb-90bd-cd77bb5d4afd.png)

**Comment by RahulParajulee** [comment]
Sorry everyone for the issue. Me and my fellow developer will soon fix this issue.

**Comment by Sulab7149** [comment]
We are currently working on that problem. We'll notice you as soon as the problem get fixed.

**Comment by Sulab7149** [comment]
Thank you for your patience @manandharsamyak. We accidently forget to update the code on CSS file. Now we've corrected the format. So, kindly check the updated code.
