### ISSUE TITLE
Data is not being store in database of 'Add Books'

### ISSUE THREAD

**Issue by NabinRayamajhi** [RahulParajulee/LibraryManagementSystem#8]
Developer, Consider working on this issue

**Comment by Sulab7149** [comment]
Thank you for the feedback. We are currently working on that issue.

**Comment by RahulParajulee** [comment]
Sorry for the inconvenience. The issue has been solved and the code is updated in the respiratory. Kindly check it.

**Comment by NabinRayamajhi** [comment]
Thank you,
